"use client";
import { useEffect, useState, useTransition } from "react";
import QRCode from "qrcode";
import { getWhatsAppDeliveryState, sendQuoteViaWhatsApp } from "@/app/quotes/whatsapp-actions";
import { primaryButtonClass } from "./ui";
type Status="PENDING"|"SENDING"|"SENT"|"DELIVERED"|"READ"|"FAILED";
const labels:Record<Status,string>={PENDING:"Pendiente",SENDING:"Enviando",SENT:"Enviado",DELIVERED:"Entregado",READ:"Leído",FAILED:"Error"};
const classes:Record<Status,string>={PENDING:"bg-warning/10 text-warning",SENDING:"bg-primary/10 text-primary-hover",SENT:"bg-success/10 text-success",DELIVERED:"bg-success/10 text-success",READ:"bg-success/10 text-success",FAILED:"bg-danger/10 text-danger"};
function terminal(s:Status|null){return s==="SENT"||s==="DELIVERED"||s==="READ";}
export function QuoteWhatsAppButton({quoteId,initialStatus=null,initialDestination=null,initialError=null}:{quoteId:string;initialStatus?:Status|null;initialDestination?:string|null;initialError?:string|null}){
 const [pending,start]=useTransition(); const [status,setStatus]=useState<Status|null>(initialStatus); const [destination,setDestination]=useState(initialDestination); const [message,setMessage]=useState(initialError); const [link,setLink]=useState<string|null>(null); const [qr,setQr]=useState<string|null>(null);
 const send=()=>{setMessage(null);start(async()=>{const r=await sendQuoteViaWhatsApp(quoteId);if(r.status)setStatus(r.status);if(r.destination)setDestination(r.destination);if(r.waLink){setLink(r.waLink);QRCode.toDataURL(r.waLink,{width:280,margin:2}).then(setQr).catch(()=>setQr(null));setMessage("Esperando mensaje del cliente...");}else if(r.error)setMessage(r.error);else setMessage("Cotización enviada por WhatsApp.");});};
 useEffect(()=>{if(!link)return;const timer=window.setInterval(()=>{getWhatsAppDeliveryState(quoteId).then(r=>{if(r.status)setStatus(r.status);if(r.destination)setDestination(r.destination);if(r.status&&terminal(r.status))window.clearInterval(timer);}).catch(()=>undefined);},2500);return()=>window.clearInterval(timer);},[link,quoteId]);
 const current=status??"PENDING"; const isTerminal=terminal(status);
 return <div className="grid gap-3"><button className={primaryButtonClass} disabled={pending||status==="SENDING"||isTerminal} onClick={send} type="button">{pending?"Preparando...":status==="FAILED"?"Reintentar envío":isTerminal?"Cotización enviada":"Enviar por WhatsApp"}</button><div className="flex flex-wrap items-center gap-2 text-sm"><span className={`rounded-full px-3 py-1 font-bold ${classes[current]}`}>WhatsApp: {labels[current]}</span>{destination?<span className="text-muted">{destination}</span>:null}</div>{link?<div className="rounded-xl border border-border p-4 text-center"><p className="font-semibold">Escanea para recibir tu cotización</p>{qr?<img className="mx-auto my-3" src={qr} alt="Código QR de WhatsApp" />:null}<p className="break-words text-xs text-muted">{link}</p><a className={`${primaryButtonClass} mt-3 inline-block`} href={link} target="_blank" rel="noreferrer">Abrir WhatsApp</a><p className="mt-2 text-sm">{message??"Esperando mensaje del cliente..."}</p></div>:null}{message&&!link?<p className={`text-sm font-semibold ${status==="FAILED"?"text-danger":"text-success"}`} role="status">{message}</p>:null}</div>;
}
