import "server-only";
import twilio from "twilio";
import { normalizeWhatsAppPhone } from "./phone";
export class TwilioConfigurationError extends Error {}
export type WhatsAppDeliveryMode = "template" | "customer_initiated";
type TwilioWhatsAppConfiguration = { accountSid:string; authToken:string; from:string; contentSid:string|null; statusCallbackUrl:string };
function requiredEnvironmentValue(name:string){const value=process.env[name]?.trim();if(!value)throw new TwilioConfigurationError(`Falta configurar ${name}.`);return value;}
function appUrl(){const value=process.env.APP_URL?.trim()||(process.env.VERCEL_URL?`https://${process.env.VERCEL_URL}`:"");if(!value)throw new TwilioConfigurationError("Falta configurar APP_URL para recibir estados de WhatsApp.");let parsed:URL;try{parsed=new URL(value);}catch{throw new TwilioConfigurationError("APP_URL debe ser una URL pÃºblica HTTPS vÃ¡lida.");}if(parsed.protocol!=="https:")throw new TwilioConfigurationError("APP_URL debe usar HTTPS para callbacks de Twilio.");return parsed.toString().replace(/\/$/,"");}
function normalizedFrom(value:string){return normalizeWhatsAppPhone(value.replace(/^whatsapp:/i,"")).whatsappAddress;}
export function twilioWhatsAppSenderToWaMeDigits(value:string){
  const source=value.trim();
  const withoutScheme=source.replace(/^whatsapp:/i,"");
  if(!/^\+[1-9]\d{6,14}$/.test(withoutScheme)) throw new TwilioConfigurationError("TWILIO_WHATSAPP_FROM debe tener formato whatsapp:+<dígitos>.");
  const digits=withoutScheme.slice(1);
  console.log("[customer initiated sender]",{senderConfigured:true,waMeDigitsValid:true,digitLength:digits.length});
  return digits;
}
export function getTwilioStatusCallbackUrl(){return `${appUrl()}/api/webhooks/twilio/whatsapp`;}
export function getTwilioInboundWebhookUrl(){return `${appUrl()}/api/webhooks/twilio/whatsapp/inbound`;}
function configuredContentSid(){return process.env.TWILIO_NAHUITECH_QUOTE_CONTENT_SID?.trim()||process.env.TWILIO_CONTENT_SID?.trim()||"";}
export function getWhatsAppDeliveryMode():WhatsAppDeliveryMode{const configuredMode=process.env.WHATSAPP_DELIVERY_MODE?.trim().toLowerCase()||"auto";if(!["template","customer_initiated","auto"].includes(configuredMode))throw new TwilioConfigurationError("WHATSAPP_DELIVERY_MODE debe ser template, customer_initiated o auto.");const sid=configuredContentSid();const valid=/^HX[a-f0-9]{32}$/i.test(sid);if(configuredMode==="template"&&!valid)throw new TwilioConfigurationError("El modo template requiere un Content SID vÃ¡lido.");const effectiveMode:WhatsAppDeliveryMode=configuredMode==="customer_initiated"||(configuredMode==="auto"&&!valid)?"customer_initiated":"template";console.log("[whatsapp delivery mode]",{configuredMode,effectiveMode});return effectiveMode;}
export function getTwilioWhatsAppConfiguration(options:{requireContentSid?:boolean}={}):TwilioWhatsAppConfiguration{const sid=configuredContentSid();const contentSid=/^HX[a-f0-9]{32}$/i.test(sid)?sid:null;if(options.requireContentSid&&!contentSid)throw new TwilioConfigurationError("El modo template requiere un Content SID vÃ¡lido.");return{accountSid:requiredEnvironmentValue("TWILIO_ACCOUNT_SID"),authToken:requiredEnvironmentValue("TWILIO_AUTH_TOKEN"),from:normalizedFrom(requiredEnvironmentValue("TWILIO_WHATSAPP_FROM")),contentSid,statusCallbackUrl:getTwilioStatusCallbackUrl()};}
function mediaVariableValue(mediaUrl:string){let parsed:URL;try{parsed=new URL(mediaUrl);}catch{throw new TwilioConfigurationError("El enlace temporal del PDF no es vÃ¡lido.");}if(parsed.protocol!=="https:")throw new TwilioConfigurationError("El enlace temporal del PDF debe usar HTTPS.");const marker="/api/whatsapp-media/";const index=parsed.pathname.indexOf(marker);const path=index<0?"":parsed.pathname.slice(index+marker.length);if(!path||path.includes("/")||parsed.search)throw new TwilioConfigurationError("El enlace temporal del PDF no tiene el formato esperado.");return path;}
export async function sendQuoteWhatsAppWithTwilio(input:{customerName:string;customerWhatsApp:string;mediaUrl:string}){const c=getTwilioWhatsAppConfiguration({requireContentSid:true});const d=normalizeWhatsAppPhone(input.customerWhatsApp);const m=await twilio(c.accountSid,c.authToken).messages.create({to:d.whatsappAddress,from:c.from,statusCallback:c.statusCallbackUrl,contentSid:c.contentSid!,contentVariables:JSON.stringify({1:input.customerName.replace(/[\r\n]/g," ").trim(),2:mediaVariableValue(input.mediaUrl)})});return{destination:d.e164,providerMessageId:m.sid};}
export async function sendCustomerInitiatedWhatsAppWithTwilio(input:{customerName:string;customerWhatsApp:string;mediaUrl:string}){const c=getTwilioWhatsAppConfiguration();const d=normalizeWhatsAppPhone(input.customerWhatsApp);const m=await twilio(c.accountSid,c.authToken).messages.create({to:d.whatsappAddress,from:c.from,body:`Hola ${input.customerName.replace(/[\r\n]/g," ").trim()}, aquí tienes tu cotización de Nahuitech. Este número se utiliza únicamente para el envío automático de cotizaciones. Para cualquier ajuste, aclaración o atención directa, comunícate con nosotros al 445 261 0873. Con gusto podemos ayudarte.`,mediaUrl:[input.mediaUrl],statusCallback:c.statusCallbackUrl});return{destination:d.e164,providerMessageId:m.sid};}
export function getWhatsAppSenderDigits(){return twilioWhatsAppSenderToWaMeDigits(requiredEnvironmentValue("TWILIO_WHATSAPP_FROM"));}
